Enclave push fix

diff --git a/.github/workflows/build-enclave.yml b/.github/workflows/build-enclave.yml
--- a/.github/workflows/build-enclave.yml
+++ b/.github/workflows/build-enclave.yml
@@ -116,12 +116,24 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE  # Move to the root directory of the repository
           mkdir -p enclave
-          # Only copy if the file does not already exist in the target path
 
+          # Ensure the new EIF file exists before proceeding
+          if [ -z "$EIF_PATH" ] || [ ! -f "$EIF_PATH" ]; then
+            echo "Error: The enclave.eif file not found at $EIF_PATH."
+            exit 1
+          fi
+
+          # Replace the existing enclave.eif file only if the source and destination are different
+          if [ "$EIF_PATH" != "$GITHUB_WORKSPACE/enclave/enclave.eif" ]; then
+            echo "Replacing existing enclave.eif with the new generated file."
             cp "$EIF_PATH" enclave/enclave.eif
+          else
+            echo "Source and destination are the same. Skipping copy."
+          fi
 
+          # Add, commit, and push changes
           git add enclave/enclave.eif
-          git commit -m "Add generated enclave.eif file" || echo "No changes to commit"
+          git commit -m "Update generated enclave.eif file" || echo "No changes to commit"
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
